In [1]:
k = 3

In [4]:
import numpy as np

In [14]:
clusters = []
for i in range(k):
    clusters.extend(np.random.rand(10,2) + i)
    

[array([0.1798635, 0.7000377]),
 array([0.03939496, 0.81562088]),
 array([0.19814754, 0.10956981]),
 array([0.47290804, 0.25569329]),
 array([0.81351271, 0.32025867]),
 array([0.8089178 , 0.80595888]),
 array([0.61570072, 0.76800887]),
 array([0.50465681, 0.75153627]),
 array([0.89304407, 0.71168959]),
 array([0.02554149, 0.21082566]),
 array([1.57351907, 1.40945265]),
 array([1.10434167, 1.70613109]),
 array([1.50047096, 1.23191636]),
 array([1.75014276, 1.39743998]),
 array([1.54182703, 1.34940899]),
 array([1.94896887, 1.21142841]),
 array([1.51479066, 1.46755404]),
 array([1.03909013, 1.78717706]),
 array([1.25609294, 1.76413226]),
 array([1.45332918, 1.03170761]),
 array([2.65011568, 2.03755698]),
 array([2.58949989, 2.56992527]),
 array([2.92194481, 2.53024091]),
 array([2.33582672, 2.50000028]),
 array([2.35030943, 2.08730884]),
 array([2.72325727, 2.02340061]),
 array([2.93927883, 2.83129706]),
 array([2.4711755 , 2.39395891]),
 array([2.40141284, 2.32875561]),
 array([2.358664